// Generated by gencpp from file whi_interfaces/PoseRegistrationResult.msg
// DO NOT EDIT!


#ifndef WHI_INTERFACES_MESSAGE_POSEREGISTRATIONRESULT_H
#define WHI_INTERFACES_MESSAGE_POSEREGISTRATIONRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace whi_interfaces
{
template <class ContainerAllocator>
struct PoseRegistrationResult_
{
  typedef PoseRegistrationResult_<ContainerAllocator> Type;

  PoseRegistrationResult_()
    : result(0)  {
    }
  PoseRegistrationResult_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(RES_SUCCEED)
  #undef RES_SUCCEED
#endif
#if defined(_WIN32) && defined(RES_FAILED)
  #undef RES_FAILED
#endif

  enum {
    RES_SUCCEED = 0u,
    RES_FAILED = 1u,
  };


  typedef boost::shared_ptr< ::whi_interfaces::PoseRegistrationResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::whi_interfaces::PoseRegistrationResult_<ContainerAllocator> const> ConstPtr;

}; // struct PoseRegistrationResult_

typedef ::whi_interfaces::PoseRegistrationResult_<std::allocator<void> > PoseRegistrationResult;

typedef boost::shared_ptr< ::whi_interfaces::PoseRegistrationResult > PoseRegistrationResultPtr;
typedef boost::shared_ptr< ::whi_interfaces::PoseRegistrationResult const> PoseRegistrationResultConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::whi_interfaces::PoseRegistrationResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::whi_interfaces::PoseRegistrationResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::whi_interfaces::PoseRegistrationResult_<ContainerAllocator1> & lhs, const ::whi_interfaces::PoseRegistrationResult_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::whi_interfaces::PoseRegistrationResult_<ContainerAllocator1> & lhs, const ::whi_interfaces::PoseRegistrationResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace whi_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::whi_interfaces::PoseRegistrationResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::whi_interfaces::PoseRegistrationResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whi_interfaces::PoseRegistrationResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whi_interfaces::PoseRegistrationResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whi_interfaces::PoseRegistrationResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whi_interfaces::PoseRegistrationResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::whi_interfaces::PoseRegistrationResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "14c541d6e20ea9bda2ff12e0262911aa";
  }

  static const char* value(const ::whi_interfaces::PoseRegistrationResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x14c541d6e20ea9bdULL;
  static const uint64_t static_value2 = 0xa2ff12e0262911aaULL;
};

template<class ContainerAllocator>
struct DataType< ::whi_interfaces::PoseRegistrationResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "whi_interfaces/PoseRegistrationResult";
  }

  static const char* value(const ::whi_interfaces::PoseRegistrationResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::whi_interfaces::PoseRegistrationResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"uint8 RES_SUCCEED=0\n"
"uint8 RES_FAILED=1\n"
"uint8 result\n"
;
  }

  static const char* value(const ::whi_interfaces::PoseRegistrationResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::whi_interfaces::PoseRegistrationResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseRegistrationResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::whi_interfaces::PoseRegistrationResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::whi_interfaces::PoseRegistrationResult_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHI_INTERFACES_MESSAGE_POSEREGISTRATIONRESULT_H
