// Generated by gencpp from file whi_interfaces/WhiBattery.msg
// DO NOT EDIT!


#ifndef WHI_INTERFACES_MESSAGE_WHIBATTERY_H
#define WHI_INTERFACES_MESSAGE_WHIBATTERY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace whi_interfaces
{
template <class ContainerAllocator>
struct WhiBattery_
{
  typedef WhiBattery_<ContainerAllocator> Type;

  WhiBattery_()
    : header()
    , soc(0)
    , soh(0)
    , state(0)  {
    }
  WhiBattery_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , soc(0)
    , soh(0)
    , state(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _soc_type;
  _soc_type soc;

   typedef uint16_t _soh_type;
  _soh_type soh;

   typedef int8_t _state_type;
  _state_type state;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(STA_NORMAL)
  #undef STA_NORMAL
#endif
#if defined(_WIN32) && defined(STA_CHARGING)
  #undef STA_CHARGING
#endif
#if defined(_WIN32) && defined(STA_NEED_CHARGING)
  #undef STA_NEED_CHARGING
#endif
#if defined(_WIN32) && defined(STA_GOOD_FOR_TASK)
  #undef STA_GOOD_FOR_TASK
#endif
#if defined(_WIN32) && defined(STA_FULL)
  #undef STA_FULL
#endif
#if defined(_WIN32) && defined(STA_FAILURE_RECOVERING)
  #undef STA_FAILURE_RECOVERING
#endif

  enum {
    STA_NORMAL = 0u,
    STA_CHARGING = 1u,
    STA_NEED_CHARGING = 2u,
    STA_GOOD_FOR_TASK = 3u,
    STA_FULL = 4u,
    STA_FAILURE_RECOVERING = 5u,
  };


  typedef boost::shared_ptr< ::whi_interfaces::WhiBattery_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::whi_interfaces::WhiBattery_<ContainerAllocator> const> ConstPtr;

}; // struct WhiBattery_

typedef ::whi_interfaces::WhiBattery_<std::allocator<void> > WhiBattery;

typedef boost::shared_ptr< ::whi_interfaces::WhiBattery > WhiBatteryPtr;
typedef boost::shared_ptr< ::whi_interfaces::WhiBattery const> WhiBatteryConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::whi_interfaces::WhiBattery_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::whi_interfaces::WhiBattery_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::whi_interfaces::WhiBattery_<ContainerAllocator1> & lhs, const ::whi_interfaces::WhiBattery_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.soc == rhs.soc &&
    lhs.soh == rhs.soh &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::whi_interfaces::WhiBattery_<ContainerAllocator1> & lhs, const ::whi_interfaces::WhiBattery_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace whi_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::whi_interfaces::WhiBattery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::whi_interfaces::WhiBattery_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whi_interfaces::WhiBattery_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whi_interfaces::WhiBattery_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whi_interfaces::WhiBattery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whi_interfaces::WhiBattery_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::whi_interfaces::WhiBattery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3459eabd6dc37def1aa304bda6a545b4";
  }

  static const char* value(const ::whi_interfaces::WhiBattery_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3459eabd6dc37defULL;
  static const uint64_t static_value2 = 0x1aa304bda6a545b4ULL;
};

template<class ContainerAllocator>
struct DataType< ::whi_interfaces::WhiBattery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "whi_interfaces/WhiBattery";
  }

  static const char* value(const ::whi_interfaces::WhiBattery_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::whi_interfaces::WhiBattery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint16 soc\n"
"uint16 soh\n"
"uint8 STA_NORMAL=0\n"
"uint8 STA_CHARGING=1\n"
"uint8 STA_NEED_CHARGING=2\n"
"uint8 STA_GOOD_FOR_TASK=3\n"
"uint8 STA_FULL=4\n"
"uint8 STA_FAILURE_RECOVERING=5\n"
"int8 state\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::whi_interfaces::WhiBattery_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::whi_interfaces::WhiBattery_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.soc);
      stream.next(m.soh);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WhiBattery_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::whi_interfaces::WhiBattery_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::whi_interfaces::WhiBattery_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "soc: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.soc);
    s << indent << "soh: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.soh);
    s << indent << "state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHI_INTERFACES_MESSAGE_WHIBATTERY_H
