// Generated by gencpp from file whi_interfaces/WhiJointPose.msg
// DO NOT EDIT!


#ifndef WHI_INTERFACES_MESSAGE_WHIJOINTPOSE_H
#define WHI_INTERFACES_MESSAGE_WHIJOINTPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/JointState.h>
#include <moveit_msgs/JointConstraint.h>

namespace whi_interfaces
{
template <class ContainerAllocator>
struct WhiJointPose_
{
  typedef WhiJointPose_<ContainerAllocator> Type;

  WhiJointPose_()
    : joint_pose()
    , joint_constraints()
    , velocity_scale(0.0)
    , acceleration_scale(0.0)
    , is_relative(false)  {
    }
  WhiJointPose_(const ContainerAllocator& _alloc)
    : joint_pose(_alloc)
    , joint_constraints(_alloc)
    , velocity_scale(0.0)
    , acceleration_scale(0.0)
    , is_relative(false)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::JointState_<ContainerAllocator>  _joint_pose_type;
  _joint_pose_type joint_pose;

   typedef std::vector< ::moveit_msgs::JointConstraint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::moveit_msgs::JointConstraint_<ContainerAllocator> >> _joint_constraints_type;
  _joint_constraints_type joint_constraints;

   typedef double _velocity_scale_type;
  _velocity_scale_type velocity_scale;

   typedef double _acceleration_scale_type;
  _acceleration_scale_type acceleration_scale;

   typedef uint8_t _is_relative_type;
  _is_relative_type is_relative;





  typedef boost::shared_ptr< ::whi_interfaces::WhiJointPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::whi_interfaces::WhiJointPose_<ContainerAllocator> const> ConstPtr;

}; // struct WhiJointPose_

typedef ::whi_interfaces::WhiJointPose_<std::allocator<void> > WhiJointPose;

typedef boost::shared_ptr< ::whi_interfaces::WhiJointPose > WhiJointPosePtr;
typedef boost::shared_ptr< ::whi_interfaces::WhiJointPose const> WhiJointPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::whi_interfaces::WhiJointPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::whi_interfaces::WhiJointPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::whi_interfaces::WhiJointPose_<ContainerAllocator1> & lhs, const ::whi_interfaces::WhiJointPose_<ContainerAllocator2> & rhs)
{
  return lhs.joint_pose == rhs.joint_pose &&
    lhs.joint_constraints == rhs.joint_constraints &&
    lhs.velocity_scale == rhs.velocity_scale &&
    lhs.acceleration_scale == rhs.acceleration_scale &&
    lhs.is_relative == rhs.is_relative;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::whi_interfaces::WhiJointPose_<ContainerAllocator1> & lhs, const ::whi_interfaces::WhiJointPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace whi_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::whi_interfaces::WhiJointPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::whi_interfaces::WhiJointPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whi_interfaces::WhiJointPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whi_interfaces::WhiJointPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whi_interfaces::WhiJointPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whi_interfaces::WhiJointPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::whi_interfaces::WhiJointPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4d4b7c6e8d1edf04f19e65b1ff509b38";
  }

  static const char* value(const ::whi_interfaces::WhiJointPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4d4b7c6e8d1edf04ULL;
  static const uint64_t static_value2 = 0xf19e65b1ff509b38ULL;
};

template<class ContainerAllocator>
struct DataType< ::whi_interfaces::WhiJointPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "whi_interfaces/WhiJointPose";
  }

  static const char* value(const ::whi_interfaces::WhiJointPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::whi_interfaces::WhiJointPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/JointState joint_pose\n"
"moveit_msgs/JointConstraint[] joint_constraints\n"
"float64 velocity_scale\n"
"float64 acceleration_scale\n"
"bool is_relative\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/JointState\n"
"# This is a message that holds data to describe the state of a set of torque controlled joints. \n"
"#\n"
"# The state of each joint (revolute or prismatic) is defined by:\n"
"#  * the position of the joint (rad or m),\n"
"#  * the velocity of the joint (rad/s or m/s) and \n"
"#  * the effort that is applied in the joint (Nm or N).\n"
"#\n"
"# Each joint is uniquely identified by its name\n"
"# The header specifies the time at which the joint states were recorded. All the joint states\n"
"# in one message have to be recorded at the same time.\n"
"#\n"
"# This message consists of a multiple arrays, one for each part of the joint state. \n"
"# The goal is to make each of the fields optional. When e.g. your joints have no\n"
"# effort associated with them, you can leave the effort array empty. \n"
"#\n"
"# All arrays in this message should have the same size, or be empty.\n"
"# This is the only way to uniquely associate the joint name with the correct\n"
"# states.\n"
"\n"
"\n"
"Header header\n"
"\n"
"string[] name\n"
"float64[] position\n"
"float64[] velocity\n"
"float64[] effort\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: moveit_msgs/JointConstraint\n"
"# Constrain the position of a joint to be within a certain bound\n"
"string joint_name\n"
"\n"
"# the bound to be achieved is [position - tolerance_below, position + tolerance_above]\n"
"float64 position\n"
"float64 tolerance_above\n"
"float64 tolerance_below\n"
"\n"
"# A weighting factor for this constraint (denotes relative importance to other constraints. Closer to zero means less important)\n"
"float64 weight\n"
;
  }

  static const char* value(const ::whi_interfaces::WhiJointPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::whi_interfaces::WhiJointPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_pose);
      stream.next(m.joint_constraints);
      stream.next(m.velocity_scale);
      stream.next(m.acceleration_scale);
      stream.next(m.is_relative);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WhiJointPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::whi_interfaces::WhiJointPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::whi_interfaces::WhiJointPose_<ContainerAllocator>& v)
  {
    s << indent << "joint_pose: ";
    s << std::endl;
    Printer< ::sensor_msgs::JointState_<ContainerAllocator> >::stream(s, indent + "  ", v.joint_pose);
    s << indent << "joint_constraints[]" << std::endl;
    for (size_t i = 0; i < v.joint_constraints.size(); ++i)
    {
      s << indent << "  joint_constraints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::moveit_msgs::JointConstraint_<ContainerAllocator> >::stream(s, indent + "    ", v.joint_constraints[i]);
    }
    s << indent << "velocity_scale: ";
    Printer<double>::stream(s, indent + "  ", v.velocity_scale);
    s << indent << "acceleration_scale: ";
    Printer<double>::stream(s, indent + "  ", v.acceleration_scale);
    s << indent << "is_relative: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_relative);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHI_INTERFACES_MESSAGE_WHIJOINTPOSE_H
