// Generated by gencpp from file whi_interfaces/WhiRcState.msg
// DO NOT EDIT!


#ifndef WHI_INTERFACES_MESSAGE_WHIRCSTATE_H
#define WHI_INTERFACES_MESSAGE_WHIRCSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace whi_interfaces
{
template <class ContainerAllocator>
struct WhiRcState_
{
  typedef WhiRcState_<ContainerAllocator> Type;

  WhiRcState_()
    : header()
    , state(0)  {
    }
  WhiRcState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _state_type;
  _state_type state;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(STA_REMOTE)
  #undef STA_REMOTE
#endif
#if defined(_WIN32) && defined(STA_AUTO)
  #undef STA_AUTO
#endif
#if defined(_WIN32) && defined(STA_CLEAR_FAULT)
  #undef STA_CLEAR_FAULT
#endif

  enum {
    STA_REMOTE = 0u,
    STA_AUTO = 1u,
    STA_CLEAR_FAULT = 3u,
  };


  typedef boost::shared_ptr< ::whi_interfaces::WhiRcState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::whi_interfaces::WhiRcState_<ContainerAllocator> const> ConstPtr;

}; // struct WhiRcState_

typedef ::whi_interfaces::WhiRcState_<std::allocator<void> > WhiRcState;

typedef boost::shared_ptr< ::whi_interfaces::WhiRcState > WhiRcStatePtr;
typedef boost::shared_ptr< ::whi_interfaces::WhiRcState const> WhiRcStateConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::whi_interfaces::WhiRcState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::whi_interfaces::WhiRcState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::whi_interfaces::WhiRcState_<ContainerAllocator1> & lhs, const ::whi_interfaces::WhiRcState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::whi_interfaces::WhiRcState_<ContainerAllocator1> & lhs, const ::whi_interfaces::WhiRcState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace whi_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::whi_interfaces::WhiRcState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::whi_interfaces::WhiRcState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whi_interfaces::WhiRcState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whi_interfaces::WhiRcState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whi_interfaces::WhiRcState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whi_interfaces::WhiRcState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::whi_interfaces::WhiRcState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "077256083eac163c4a7899965f98951e";
  }

  static const char* value(const ::whi_interfaces::WhiRcState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x077256083eac163cULL;
  static const uint64_t static_value2 = 0x4a7899965f98951eULL;
};

template<class ContainerAllocator>
struct DataType< ::whi_interfaces::WhiRcState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "whi_interfaces/WhiRcState";
  }

  static const char* value(const ::whi_interfaces::WhiRcState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::whi_interfaces::WhiRcState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint8 state\n"
"uint8 STA_REMOTE=0\n"
"uint8 STA_AUTO=1\n"
"uint8 STA_CLEAR_FAULT=3\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::whi_interfaces::WhiRcState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::whi_interfaces::WhiRcState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WhiRcState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::whi_interfaces::WhiRcState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::whi_interfaces::WhiRcState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHI_INTERFACES_MESSAGE_WHIRCSTATE_H
