// Generated by gencpp from file whi_interfaces/WhiSrvQrcodeResponse.msg
// DO NOT EDIT!


#ifndef WHI_INTERFACES_MESSAGE_WHISRVQRCODERESPONSE_H
#define WHI_INTERFACES_MESSAGE_WHISRVQRCODERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace whi_interfaces
{
template <class ContainerAllocator>
struct WhiSrvQrcodeResponse_
{
  typedef WhiSrvQrcodeResponse_<ContainerAllocator> Type;

  WhiSrvQrcodeResponse_()
    : code()
    , offset_pose()
    , eulers()
    , eulers_degree()  {
    }
  WhiSrvQrcodeResponse_(const ContainerAllocator& _alloc)
    : code(_alloc)
    , offset_pose(_alloc)
    , eulers(_alloc)
    , eulers_degree(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _code_type;
  _code_type code;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _offset_pose_type;
  _offset_pose_type offset_pose;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _eulers_type;
  _eulers_type eulers;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _eulers_degree_type;
  _eulers_degree_type eulers_degree;





  typedef boost::shared_ptr< ::whi_interfaces::WhiSrvQrcodeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::whi_interfaces::WhiSrvQrcodeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WhiSrvQrcodeResponse_

typedef ::whi_interfaces::WhiSrvQrcodeResponse_<std::allocator<void> > WhiSrvQrcodeResponse;

typedef boost::shared_ptr< ::whi_interfaces::WhiSrvQrcodeResponse > WhiSrvQrcodeResponsePtr;
typedef boost::shared_ptr< ::whi_interfaces::WhiSrvQrcodeResponse const> WhiSrvQrcodeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::whi_interfaces::WhiSrvQrcodeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::whi_interfaces::WhiSrvQrcodeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::whi_interfaces::WhiSrvQrcodeResponse_<ContainerAllocator1> & lhs, const ::whi_interfaces::WhiSrvQrcodeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.code == rhs.code &&
    lhs.offset_pose == rhs.offset_pose &&
    lhs.eulers == rhs.eulers &&
    lhs.eulers_degree == rhs.eulers_degree;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::whi_interfaces::WhiSrvQrcodeResponse_<ContainerAllocator1> & lhs, const ::whi_interfaces::WhiSrvQrcodeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace whi_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::whi_interfaces::WhiSrvQrcodeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::whi_interfaces::WhiSrvQrcodeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whi_interfaces::WhiSrvQrcodeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whi_interfaces::WhiSrvQrcodeResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whi_interfaces::WhiSrvQrcodeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whi_interfaces::WhiSrvQrcodeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::whi_interfaces::WhiSrvQrcodeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "45d686393cd6209b1ac820f9284812a3";
  }

  static const char* value(const ::whi_interfaces::WhiSrvQrcodeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x45d686393cd6209bULL;
  static const uint64_t static_value2 = 0x1ac820f9284812a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::whi_interfaces::WhiSrvQrcodeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "whi_interfaces/WhiSrvQrcodeResponse";
  }

  static const char* value(const ::whi_interfaces::WhiSrvQrcodeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::whi_interfaces::WhiSrvQrcodeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string code\n"
"geometry_msgs/PoseStamped offset_pose\n"
"float64[] eulers\n"
"float64[] eulers_degree\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::whi_interfaces::WhiSrvQrcodeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::whi_interfaces::WhiSrvQrcodeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.code);
      stream.next(m.offset_pose);
      stream.next(m.eulers);
      stream.next(m.eulers_degree);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WhiSrvQrcodeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::whi_interfaces::WhiSrvQrcodeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::whi_interfaces::WhiSrvQrcodeResponse_<ContainerAllocator>& v)
  {
    s << indent << "code: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.code);
    s << indent << "offset_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.offset_pose);
    s << indent << "eulers[]" << std::endl;
    for (size_t i = 0; i < v.eulers.size(); ++i)
    {
      s << indent << "  eulers[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.eulers[i]);
    }
    s << indent << "eulers_degree[]" << std::endl;
    for (size_t i = 0; i < v.eulers_degree.size(); ++i)
    {
      s << indent << "  eulers_degree[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.eulers_degree[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHI_INTERFACES_MESSAGE_WHISRVQRCODERESPONSE_H
