// Generated by gencpp from file whi_interfaces/WhiSrvIndicator.msg
// DO NOT EDIT!


#ifndef WHI_INTERFACES_MESSAGE_WHISRVINDICATOR_H
#define WHI_INTERFACES_MESSAGE_WHISRVINDICATOR_H

#include <ros/service_traits.h>


#include <whi_interfaces/WhiSrvIndicatorRequest.h>
#include <whi_interfaces/WhiSrvIndicatorResponse.h>


namespace whi_interfaces
{

struct WhiSrvIndicator
{

typedef WhiSrvIndicatorRequest Request;
typedef WhiSrvIndicatorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WhiSrvIndicator
} // namespace whi_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::whi_interfaces::WhiSrvIndicator > {
  static const char* value()
  {
    return "ec1649436397c99428e3f4dff37492e6";
  }

  static const char* value(const ::whi_interfaces::WhiSrvIndicator&) { return value(); }
};

template<>
struct DataType< ::whi_interfaces::WhiSrvIndicator > {
  static const char* value()
  {
    return "whi_interfaces/WhiSrvIndicator";
  }

  static const char* value(const ::whi_interfaces::WhiSrvIndicator&) { return value(); }
};


// service_traits::MD5Sum< ::whi_interfaces::WhiSrvIndicatorRequest> should match
// service_traits::MD5Sum< ::whi_interfaces::WhiSrvIndicator >
template<>
struct MD5Sum< ::whi_interfaces::WhiSrvIndicatorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::whi_interfaces::WhiSrvIndicator >::value();
  }
  static const char* value(const ::whi_interfaces::WhiSrvIndicatorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::whi_interfaces::WhiSrvIndicatorRequest> should match
// service_traits::DataType< ::whi_interfaces::WhiSrvIndicator >
template<>
struct DataType< ::whi_interfaces::WhiSrvIndicatorRequest>
{
  static const char* value()
  {
    return DataType< ::whi_interfaces::WhiSrvIndicator >::value();
  }
  static const char* value(const ::whi_interfaces::WhiSrvIndicatorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::whi_interfaces::WhiSrvIndicatorResponse> should match
// service_traits::MD5Sum< ::whi_interfaces::WhiSrvIndicator >
template<>
struct MD5Sum< ::whi_interfaces::WhiSrvIndicatorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::whi_interfaces::WhiSrvIndicator >::value();
  }
  static const char* value(const ::whi_interfaces::WhiSrvIndicatorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::whi_interfaces::WhiSrvIndicatorResponse> should match
// service_traits::DataType< ::whi_interfaces::WhiSrvIndicator >
template<>
struct DataType< ::whi_interfaces::WhiSrvIndicatorResponse>
{
  static const char* value()
  {
    return DataType< ::whi_interfaces::WhiSrvIndicator >::value();
  }
  static const char* value(const ::whi_interfaces::WhiSrvIndicatorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WHI_INTERFACES_MESSAGE_WHISRVINDICATOR_H
