// Generated by gencpp from file whi_interfaces/WhiSrvTcpPose.msg
// DO NOT EDIT!


#ifndef WHI_INTERFACES_MESSAGE_WHISRVTCPPOSE_H
#define WHI_INTERFACES_MESSAGE_WHISRVTCPPOSE_H

#include <ros/service_traits.h>


#include <whi_interfaces/WhiSrvTcpPoseRequest.h>
#include <whi_interfaces/WhiSrvTcpPoseResponse.h>


namespace whi_interfaces
{

struct WhiSrvTcpPose
{

typedef WhiSrvTcpPoseRequest Request;
typedef WhiSrvTcpPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WhiSrvTcpPose
} // namespace whi_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::whi_interfaces::WhiSrvTcpPose > {
  static const char* value()
  {
    return "02c8b6908754e6d9bbc689bc093a0d87";
  }

  static const char* value(const ::whi_interfaces::WhiSrvTcpPose&) { return value(); }
};

template<>
struct DataType< ::whi_interfaces::WhiSrvTcpPose > {
  static const char* value()
  {
    return "whi_interfaces/WhiSrvTcpPose";
  }

  static const char* value(const ::whi_interfaces::WhiSrvTcpPose&) { return value(); }
};


// service_traits::MD5Sum< ::whi_interfaces::WhiSrvTcpPoseRequest> should match
// service_traits::MD5Sum< ::whi_interfaces::WhiSrvTcpPose >
template<>
struct MD5Sum< ::whi_interfaces::WhiSrvTcpPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::whi_interfaces::WhiSrvTcpPose >::value();
  }
  static const char* value(const ::whi_interfaces::WhiSrvTcpPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::whi_interfaces::WhiSrvTcpPoseRequest> should match
// service_traits::DataType< ::whi_interfaces::WhiSrvTcpPose >
template<>
struct DataType< ::whi_interfaces::WhiSrvTcpPoseRequest>
{
  static const char* value()
  {
    return DataType< ::whi_interfaces::WhiSrvTcpPose >::value();
  }
  static const char* value(const ::whi_interfaces::WhiSrvTcpPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::whi_interfaces::WhiSrvTcpPoseResponse> should match
// service_traits::MD5Sum< ::whi_interfaces::WhiSrvTcpPose >
template<>
struct MD5Sum< ::whi_interfaces::WhiSrvTcpPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::whi_interfaces::WhiSrvTcpPose >::value();
  }
  static const char* value(const ::whi_interfaces::WhiSrvTcpPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::whi_interfaces::WhiSrvTcpPoseResponse> should match
// service_traits::DataType< ::whi_interfaces::WhiSrvTcpPose >
template<>
struct DataType< ::whi_interfaces::WhiSrvTcpPoseResponse>
{
  static const char* value()
  {
    return DataType< ::whi_interfaces::WhiSrvTcpPose >::value();
  }
  static const char* value(const ::whi_interfaces::WhiSrvTcpPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WHI_INTERFACES_MESSAGE_WHISRVTCPPOSE_H
