// Generated by gencpp from file whi_interfaces/WhiSrvJointNamesRequest.msg
// DO NOT EDIT!


#ifndef WHI_INTERFACES_MESSAGE_WHISRVJOINTNAMESREQUEST_H
#define WHI_INTERFACES_MESSAGE_WHISRVJOINTNAMESREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace whi_interfaces
{
template <class ContainerAllocator>
struct WhiSrvJointNamesRequest_
{
  typedef WhiSrvJointNamesRequest_<ContainerAllocator> Type;

  WhiSrvJointNamesRequest_()
    {
    }
  WhiSrvJointNamesRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::whi_interfaces::WhiSrvJointNamesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::whi_interfaces::WhiSrvJointNamesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WhiSrvJointNamesRequest_

typedef ::whi_interfaces::WhiSrvJointNamesRequest_<std::allocator<void> > WhiSrvJointNamesRequest;

typedef boost::shared_ptr< ::whi_interfaces::WhiSrvJointNamesRequest > WhiSrvJointNamesRequestPtr;
typedef boost::shared_ptr< ::whi_interfaces::WhiSrvJointNamesRequest const> WhiSrvJointNamesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::whi_interfaces::WhiSrvJointNamesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::whi_interfaces::WhiSrvJointNamesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace whi_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::whi_interfaces::WhiSrvJointNamesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::whi_interfaces::WhiSrvJointNamesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whi_interfaces::WhiSrvJointNamesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whi_interfaces::WhiSrvJointNamesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whi_interfaces::WhiSrvJointNamesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whi_interfaces::WhiSrvJointNamesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::whi_interfaces::WhiSrvJointNamesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::whi_interfaces::WhiSrvJointNamesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::whi_interfaces::WhiSrvJointNamesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "whi_interfaces/WhiSrvJointNamesRequest";
  }

  static const char* value(const ::whi_interfaces::WhiSrvJointNamesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::whi_interfaces::WhiSrvJointNamesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::whi_interfaces::WhiSrvJointNamesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::whi_interfaces::WhiSrvJointNamesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WhiSrvJointNamesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::whi_interfaces::WhiSrvJointNamesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::whi_interfaces::WhiSrvJointNamesRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // WHI_INTERFACES_MESSAGE_WHISRVJOINTNAMESREQUEST_H
