// Generated by gencpp from file whi_interfaces/WhiSrvIoRequest.msg
// DO NOT EDIT!


#ifndef WHI_INTERFACES_MESSAGE_WHISRVIOREQUEST_H
#define WHI_INTERFACES_MESSAGE_WHISRVIOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace whi_interfaces
{
template <class ContainerAllocator>
struct WhiSrvIoRequest_
{
  typedef WhiSrvIoRequest_<ContainerAllocator> Type;

  WhiSrvIoRequest_()
    : name()
    , addr(0)
    , level(0)
    , operation(0)  {
    }
  WhiSrvIoRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , addr(0)
    , level(0)
    , operation(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef int32_t _addr_type;
  _addr_type addr;

   typedef uint8_t _level_type;
  _level_type level;

   typedef uint8_t _operation_type;
  _operation_type operation;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(OPER_READ)
  #undef OPER_READ
#endif
#if defined(_WIN32) && defined(OPER_WRITE)
  #undef OPER_WRITE
#endif

  enum {
    OPER_READ = 0u,
    OPER_WRITE = 1u,
  };


  typedef boost::shared_ptr< ::whi_interfaces::WhiSrvIoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::whi_interfaces::WhiSrvIoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WhiSrvIoRequest_

typedef ::whi_interfaces::WhiSrvIoRequest_<std::allocator<void> > WhiSrvIoRequest;

typedef boost::shared_ptr< ::whi_interfaces::WhiSrvIoRequest > WhiSrvIoRequestPtr;
typedef boost::shared_ptr< ::whi_interfaces::WhiSrvIoRequest const> WhiSrvIoRequestConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::whi_interfaces::WhiSrvIoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::whi_interfaces::WhiSrvIoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::whi_interfaces::WhiSrvIoRequest_<ContainerAllocator1> & lhs, const ::whi_interfaces::WhiSrvIoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.addr == rhs.addr &&
    lhs.level == rhs.level &&
    lhs.operation == rhs.operation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::whi_interfaces::WhiSrvIoRequest_<ContainerAllocator1> & lhs, const ::whi_interfaces::WhiSrvIoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace whi_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::whi_interfaces::WhiSrvIoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::whi_interfaces::WhiSrvIoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whi_interfaces::WhiSrvIoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whi_interfaces::WhiSrvIoRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whi_interfaces::WhiSrvIoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whi_interfaces::WhiSrvIoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::whi_interfaces::WhiSrvIoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a835c885cd8a6dc87db1517c19407204";
  }

  static const char* value(const ::whi_interfaces::WhiSrvIoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa835c885cd8a6dc8ULL;
  static const uint64_t static_value2 = 0x7db1517c19407204ULL;
};

template<class ContainerAllocator>
struct DataType< ::whi_interfaces::WhiSrvIoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "whi_interfaces/WhiSrvIoRequest";
  }

  static const char* value(const ::whi_interfaces::WhiSrvIoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::whi_interfaces::WhiSrvIoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 OPER_READ=0\n"
"uint8 OPER_WRITE=1\n"
"string name\n"
"int32 addr\n"
"uint8 level\n"
"uint8 operation\n"
;
  }

  static const char* value(const ::whi_interfaces::WhiSrvIoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::whi_interfaces::WhiSrvIoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.addr);
      stream.next(m.level);
      stream.next(m.operation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WhiSrvIoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::whi_interfaces::WhiSrvIoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::whi_interfaces::WhiSrvIoRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "addr: ";
    Printer<int32_t>::stream(s, indent + "  ", v.addr);
    s << indent << "level: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.level);
    s << indent << "operation: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.operation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHI_INTERFACES_MESSAGE_WHISRVIOREQUEST_H
