// Generated by gencpp from file whi_interfaces/WhiSrvIoResponse.msg
// DO NOT EDIT!


#ifndef WHI_INTERFACES_MESSAGE_WHISRVIORESPONSE_H
#define WHI_INTERFACES_MESSAGE_WHISRVIORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace whi_interfaces
{
template <class ContainerAllocator>
struct WhiSrvIoResponse_
{
  typedef WhiSrvIoResponse_<ContainerAllocator> Type;

  WhiSrvIoResponse_()
    : level(0)
    , result(false)  {
    }
  WhiSrvIoResponse_(const ContainerAllocator& _alloc)
    : level(0)
    , result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _level_type;
  _level_type level;

   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::whi_interfaces::WhiSrvIoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::whi_interfaces::WhiSrvIoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WhiSrvIoResponse_

typedef ::whi_interfaces::WhiSrvIoResponse_<std::allocator<void> > WhiSrvIoResponse;

typedef boost::shared_ptr< ::whi_interfaces::WhiSrvIoResponse > WhiSrvIoResponsePtr;
typedef boost::shared_ptr< ::whi_interfaces::WhiSrvIoResponse const> WhiSrvIoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::whi_interfaces::WhiSrvIoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::whi_interfaces::WhiSrvIoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::whi_interfaces::WhiSrvIoResponse_<ContainerAllocator1> & lhs, const ::whi_interfaces::WhiSrvIoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.level == rhs.level &&
    lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::whi_interfaces::WhiSrvIoResponse_<ContainerAllocator1> & lhs, const ::whi_interfaces::WhiSrvIoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace whi_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::whi_interfaces::WhiSrvIoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::whi_interfaces::WhiSrvIoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whi_interfaces::WhiSrvIoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whi_interfaces::WhiSrvIoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whi_interfaces::WhiSrvIoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whi_interfaces::WhiSrvIoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::whi_interfaces::WhiSrvIoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ff0aa5cf2c882e2f42c447f724082b0";
  }

  static const char* value(const ::whi_interfaces::WhiSrvIoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ff0aa5cf2c882e2ULL;
  static const uint64_t static_value2 = 0xf42c447f724082b0ULL;
};

template<class ContainerAllocator>
struct DataType< ::whi_interfaces::WhiSrvIoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "whi_interfaces/WhiSrvIoResponse";
  }

  static const char* value(const ::whi_interfaces::WhiSrvIoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::whi_interfaces::WhiSrvIoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 level\n"
"bool result\n"
;
  }

  static const char* value(const ::whi_interfaces::WhiSrvIoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::whi_interfaces::WhiSrvIoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.level);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WhiSrvIoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::whi_interfaces::WhiSrvIoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::whi_interfaces::WhiSrvIoResponse_<ContainerAllocator>& v)
  {
    s << indent << "level: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.level);
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHI_INTERFACES_MESSAGE_WHISRVIORESPONSE_H
