// Generated by gencpp from file whi_interfaces/WhiSrvIo.msg
// DO NOT EDIT!


#ifndef WHI_INTERFACES_MESSAGE_WHISRVIO_H
#define WHI_INTERFACES_MESSAGE_WHISRVIO_H

#include <ros/service_traits.h>


#include <whi_interfaces/WhiSrvIoRequest.h>
#include <whi_interfaces/WhiSrvIoResponse.h>


namespace whi_interfaces
{

struct WhiSrvIo
{

typedef WhiSrvIoRequest Request;
typedef WhiSrvIoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WhiSrvIo
} // namespace whi_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::whi_interfaces::WhiSrvIo > {
  static const char* value()
  {
    return "06304a0a11512b6f81b205a97a00fb19";
  }

  static const char* value(const ::whi_interfaces::WhiSrvIo&) { return value(); }
};

template<>
struct DataType< ::whi_interfaces::WhiSrvIo > {
  static const char* value()
  {
    return "whi_interfaces/WhiSrvIo";
  }

  static const char* value(const ::whi_interfaces::WhiSrvIo&) { return value(); }
};


// service_traits::MD5Sum< ::whi_interfaces::WhiSrvIoRequest> should match
// service_traits::MD5Sum< ::whi_interfaces::WhiSrvIo >
template<>
struct MD5Sum< ::whi_interfaces::WhiSrvIoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::whi_interfaces::WhiSrvIo >::value();
  }
  static const char* value(const ::whi_interfaces::WhiSrvIoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::whi_interfaces::WhiSrvIoRequest> should match
// service_traits::DataType< ::whi_interfaces::WhiSrvIo >
template<>
struct DataType< ::whi_interfaces::WhiSrvIoRequest>
{
  static const char* value()
  {
    return DataType< ::whi_interfaces::WhiSrvIo >::value();
  }
  static const char* value(const ::whi_interfaces::WhiSrvIoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::whi_interfaces::WhiSrvIoResponse> should match
// service_traits::MD5Sum< ::whi_interfaces::WhiSrvIo >
template<>
struct MD5Sum< ::whi_interfaces::WhiSrvIoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::whi_interfaces::WhiSrvIo >::value();
  }
  static const char* value(const ::whi_interfaces::WhiSrvIoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::whi_interfaces::WhiSrvIoResponse> should match
// service_traits::DataType< ::whi_interfaces::WhiSrvIo >
template<>
struct DataType< ::whi_interfaces::WhiSrvIoResponse>
{
  static const char* value()
  {
    return DataType< ::whi_interfaces::WhiSrvIo >::value();
  }
  static const char* value(const ::whi_interfaces::WhiSrvIoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WHI_INTERFACES_MESSAGE_WHISRVIO_H
