// Generated by gencpp from file whi_interfaces/WhiSrvQrcode.msg
// DO NOT EDIT!


#ifndef WHI_INTERFACES_MESSAGE_WHISRVQRCODE_H
#define WHI_INTERFACES_MESSAGE_WHISRVQRCODE_H

#include <ros/service_traits.h>


#include <whi_interfaces/WhiSrvQrcodeRequest.h>
#include <whi_interfaces/WhiSrvQrcodeResponse.h>


namespace whi_interfaces
{

struct WhiSrvQrcode
{

typedef WhiSrvQrcodeRequest Request;
typedef WhiSrvQrcodeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WhiSrvQrcode
} // namespace whi_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::whi_interfaces::WhiSrvQrcode > {
  static const char* value()
  {
    return "7a9928f647b8395ed6c3faa691d3de34";
  }

  static const char* value(const ::whi_interfaces::WhiSrvQrcode&) { return value(); }
};

template<>
struct DataType< ::whi_interfaces::WhiSrvQrcode > {
  static const char* value()
  {
    return "whi_interfaces/WhiSrvQrcode";
  }

  static const char* value(const ::whi_interfaces::WhiSrvQrcode&) { return value(); }
};


// service_traits::MD5Sum< ::whi_interfaces::WhiSrvQrcodeRequest> should match
// service_traits::MD5Sum< ::whi_interfaces::WhiSrvQrcode >
template<>
struct MD5Sum< ::whi_interfaces::WhiSrvQrcodeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::whi_interfaces::WhiSrvQrcode >::value();
  }
  static const char* value(const ::whi_interfaces::WhiSrvQrcodeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::whi_interfaces::WhiSrvQrcodeRequest> should match
// service_traits::DataType< ::whi_interfaces::WhiSrvQrcode >
template<>
struct DataType< ::whi_interfaces::WhiSrvQrcodeRequest>
{
  static const char* value()
  {
    return DataType< ::whi_interfaces::WhiSrvQrcode >::value();
  }
  static const char* value(const ::whi_interfaces::WhiSrvQrcodeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::whi_interfaces::WhiSrvQrcodeResponse> should match
// service_traits::MD5Sum< ::whi_interfaces::WhiSrvQrcode >
template<>
struct MD5Sum< ::whi_interfaces::WhiSrvQrcodeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::whi_interfaces::WhiSrvQrcode >::value();
  }
  static const char* value(const ::whi_interfaces::WhiSrvQrcodeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::whi_interfaces::WhiSrvQrcodeResponse> should match
// service_traits::DataType< ::whi_interfaces::WhiSrvQrcode >
template<>
struct DataType< ::whi_interfaces::WhiSrvQrcodeResponse>
{
  static const char* value()
  {
    return DataType< ::whi_interfaces::WhiSrvQrcode >::value();
  }
  static const char* value(const ::whi_interfaces::WhiSrvQrcodeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WHI_INTERFACES_MESSAGE_WHISRVQRCODE_H
