// Generated by gencpp from file whi_interfaces/WhiSrvMotionOffsetsRequest.msg
// DO NOT EDIT!


#ifndef WHI_INTERFACES_MESSAGE_WHISRVMOTIONOFFSETSREQUEST_H
#define WHI_INTERFACES_MESSAGE_WHISRVMOTIONOFFSETSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace whi_interfaces
{
template <class ContainerAllocator>
struct WhiSrvMotionOffsetsRequest_
{
  typedef WhiSrvMotionOffsetsRequest_<ContainerAllocator> Type;

  WhiSrvMotionOffsetsRequest_()
    : offsets()  {
    }
  WhiSrvMotionOffsetsRequest_(const ContainerAllocator& _alloc)
    : offsets(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _offsets_type;
  _offsets_type offsets;





  typedef boost::shared_ptr< ::whi_interfaces::WhiSrvMotionOffsetsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::whi_interfaces::WhiSrvMotionOffsetsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WhiSrvMotionOffsetsRequest_

typedef ::whi_interfaces::WhiSrvMotionOffsetsRequest_<std::allocator<void> > WhiSrvMotionOffsetsRequest;

typedef boost::shared_ptr< ::whi_interfaces::WhiSrvMotionOffsetsRequest > WhiSrvMotionOffsetsRequestPtr;
typedef boost::shared_ptr< ::whi_interfaces::WhiSrvMotionOffsetsRequest const> WhiSrvMotionOffsetsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::whi_interfaces::WhiSrvMotionOffsetsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::whi_interfaces::WhiSrvMotionOffsetsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::whi_interfaces::WhiSrvMotionOffsetsRequest_<ContainerAllocator1> & lhs, const ::whi_interfaces::WhiSrvMotionOffsetsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.offsets == rhs.offsets;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::whi_interfaces::WhiSrvMotionOffsetsRequest_<ContainerAllocator1> & lhs, const ::whi_interfaces::WhiSrvMotionOffsetsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace whi_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::whi_interfaces::WhiSrvMotionOffsetsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::whi_interfaces::WhiSrvMotionOffsetsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whi_interfaces::WhiSrvMotionOffsetsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whi_interfaces::WhiSrvMotionOffsetsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whi_interfaces::WhiSrvMotionOffsetsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whi_interfaces::WhiSrvMotionOffsetsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::whi_interfaces::WhiSrvMotionOffsetsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "df25723a27fb975e1af9bf285d3d84cb";
  }

  static const char* value(const ::whi_interfaces::WhiSrvMotionOffsetsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdf25723a27fb975eULL;
  static const uint64_t static_value2 = 0x1af9bf285d3d84cbULL;
};

template<class ContainerAllocator>
struct DataType< ::whi_interfaces::WhiSrvMotionOffsetsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "whi_interfaces/WhiSrvMotionOffsetsRequest";
  }

  static const char* value(const ::whi_interfaces::WhiSrvMotionOffsetsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::whi_interfaces::WhiSrvMotionOffsetsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] offsets\n"
;
  }

  static const char* value(const ::whi_interfaces::WhiSrvMotionOffsetsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::whi_interfaces::WhiSrvMotionOffsetsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.offsets);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WhiSrvMotionOffsetsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::whi_interfaces::WhiSrvMotionOffsetsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::whi_interfaces::WhiSrvMotionOffsetsRequest_<ContainerAllocator>& v)
  {
    s << indent << "offsets[]" << std::endl;
    for (size_t i = 0; i < v.offsets.size(); ++i)
    {
      s << indent << "  offsets[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.offsets[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHI_INTERFACES_MESSAGE_WHISRVMOTIONOFFSETSREQUEST_H
