// Generated by gencpp from file whi_interfaces/WhiSrvQrcodeRequest.msg
// DO NOT EDIT!


#ifndef WHI_INTERFACES_MESSAGE_WHISRVQRCODEREQUEST_H
#define WHI_INTERFACES_MESSAGE_WHISRVQRCODEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace whi_interfaces
{
template <class ContainerAllocator>
struct WhiSrvQrcodeRequest_
{
  typedef WhiSrvQrcodeRequest_<ContainerAllocator> Type;

  WhiSrvQrcodeRequest_()
    : count(0)  {
    }
  WhiSrvQrcodeRequest_(const ContainerAllocator& _alloc)
    : count(0)  {
  (void)_alloc;
    }



   typedef int32_t _count_type;
  _count_type count;





  typedef boost::shared_ptr< ::whi_interfaces::WhiSrvQrcodeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::whi_interfaces::WhiSrvQrcodeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WhiSrvQrcodeRequest_

typedef ::whi_interfaces::WhiSrvQrcodeRequest_<std::allocator<void> > WhiSrvQrcodeRequest;

typedef boost::shared_ptr< ::whi_interfaces::WhiSrvQrcodeRequest > WhiSrvQrcodeRequestPtr;
typedef boost::shared_ptr< ::whi_interfaces::WhiSrvQrcodeRequest const> WhiSrvQrcodeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::whi_interfaces::WhiSrvQrcodeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::whi_interfaces::WhiSrvQrcodeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::whi_interfaces::WhiSrvQrcodeRequest_<ContainerAllocator1> & lhs, const ::whi_interfaces::WhiSrvQrcodeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.count == rhs.count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::whi_interfaces::WhiSrvQrcodeRequest_<ContainerAllocator1> & lhs, const ::whi_interfaces::WhiSrvQrcodeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace whi_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::whi_interfaces::WhiSrvQrcodeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::whi_interfaces::WhiSrvQrcodeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whi_interfaces::WhiSrvQrcodeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whi_interfaces::WhiSrvQrcodeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whi_interfaces::WhiSrvQrcodeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whi_interfaces::WhiSrvQrcodeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::whi_interfaces::WhiSrvQrcodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "602d642babe509c7c59f497c23e716a9";
  }

  static const char* value(const ::whi_interfaces::WhiSrvQrcodeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x602d642babe509c7ULL;
  static const uint64_t static_value2 = 0xc59f497c23e716a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::whi_interfaces::WhiSrvQrcodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "whi_interfaces/WhiSrvQrcodeRequest";
  }

  static const char* value(const ::whi_interfaces::WhiSrvQrcodeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::whi_interfaces::WhiSrvQrcodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 count\n"
;
  }

  static const char* value(const ::whi_interfaces::WhiSrvQrcodeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::whi_interfaces::WhiSrvQrcodeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WhiSrvQrcodeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::whi_interfaces::WhiSrvQrcodeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::whi_interfaces::WhiSrvQrcodeRequest_<ContainerAllocator>& v)
  {
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHI_INTERFACES_MESSAGE_WHISRVQRCODEREQUEST_H
