// Generated by gencpp from file whi_interfaces/WhiSrvIndicatorResponse.msg
// DO NOT EDIT!


#ifndef WHI_INTERFACES_MESSAGE_WHISRVINDICATORRESPONSE_H
#define WHI_INTERFACES_MESSAGE_WHISRVINDICATORRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace whi_interfaces
{
template <class ContainerAllocator>
struct WhiSrvIndicatorResponse_
{
  typedef WhiSrvIndicatorResponse_<ContainerAllocator> Type;

  WhiSrvIndicatorResponse_()
    : status(0)
    , result(false)  {
    }
  WhiSrvIndicatorResponse_(const ContainerAllocator& _alloc)
    : status(0)
    , result(false)  {
  (void)_alloc;
    }



   typedef uint32_t _status_type;
  _status_type status;

   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::whi_interfaces::WhiSrvIndicatorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::whi_interfaces::WhiSrvIndicatorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WhiSrvIndicatorResponse_

typedef ::whi_interfaces::WhiSrvIndicatorResponse_<std::allocator<void> > WhiSrvIndicatorResponse;

typedef boost::shared_ptr< ::whi_interfaces::WhiSrvIndicatorResponse > WhiSrvIndicatorResponsePtr;
typedef boost::shared_ptr< ::whi_interfaces::WhiSrvIndicatorResponse const> WhiSrvIndicatorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::whi_interfaces::WhiSrvIndicatorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::whi_interfaces::WhiSrvIndicatorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::whi_interfaces::WhiSrvIndicatorResponse_<ContainerAllocator1> & lhs, const ::whi_interfaces::WhiSrvIndicatorResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::whi_interfaces::WhiSrvIndicatorResponse_<ContainerAllocator1> & lhs, const ::whi_interfaces::WhiSrvIndicatorResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace whi_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::whi_interfaces::WhiSrvIndicatorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::whi_interfaces::WhiSrvIndicatorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whi_interfaces::WhiSrvIndicatorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whi_interfaces::WhiSrvIndicatorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whi_interfaces::WhiSrvIndicatorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whi_interfaces::WhiSrvIndicatorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::whi_interfaces::WhiSrvIndicatorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79a5b7da520d99d7730934d0a2446f08";
  }

  static const char* value(const ::whi_interfaces::WhiSrvIndicatorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79a5b7da520d99d7ULL;
  static const uint64_t static_value2 = 0x730934d0a2446f08ULL;
};

template<class ContainerAllocator>
struct DataType< ::whi_interfaces::WhiSrvIndicatorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "whi_interfaces/WhiSrvIndicatorResponse";
  }

  static const char* value(const ::whi_interfaces::WhiSrvIndicatorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::whi_interfaces::WhiSrvIndicatorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 status\n"
"bool result\n"
;
  }

  static const char* value(const ::whi_interfaces::WhiSrvIndicatorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::whi_interfaces::WhiSrvIndicatorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WhiSrvIndicatorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::whi_interfaces::WhiSrvIndicatorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::whi_interfaces::WhiSrvIndicatorResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.status);
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHI_INTERFACES_MESSAGE_WHISRVINDICATORRESPONSE_H
