// Generated by gencpp from file whi_interfaces/WhiSrvJointPose.msg
// DO NOT EDIT!


#ifndef WHI_INTERFACES_MESSAGE_WHISRVJOINTPOSE_H
#define WHI_INTERFACES_MESSAGE_WHISRVJOINTPOSE_H

#include <ros/service_traits.h>


#include <whi_interfaces/WhiSrvJointPoseRequest.h>
#include <whi_interfaces/WhiSrvJointPoseResponse.h>


namespace whi_interfaces
{

struct WhiSrvJointPose
{

typedef WhiSrvJointPoseRequest Request;
typedef WhiSrvJointPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WhiSrvJointPose
} // namespace whi_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::whi_interfaces::WhiSrvJointPose > {
  static const char* value()
  {
    return "7171209ddb400c1d7e51ff842e42bd1f";
  }

  static const char* value(const ::whi_interfaces::WhiSrvJointPose&) { return value(); }
};

template<>
struct DataType< ::whi_interfaces::WhiSrvJointPose > {
  static const char* value()
  {
    return "whi_interfaces/WhiSrvJointPose";
  }

  static const char* value(const ::whi_interfaces::WhiSrvJointPose&) { return value(); }
};


// service_traits::MD5Sum< ::whi_interfaces::WhiSrvJointPoseRequest> should match
// service_traits::MD5Sum< ::whi_interfaces::WhiSrvJointPose >
template<>
struct MD5Sum< ::whi_interfaces::WhiSrvJointPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::whi_interfaces::WhiSrvJointPose >::value();
  }
  static const char* value(const ::whi_interfaces::WhiSrvJointPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::whi_interfaces::WhiSrvJointPoseRequest> should match
// service_traits::DataType< ::whi_interfaces::WhiSrvJointPose >
template<>
struct DataType< ::whi_interfaces::WhiSrvJointPoseRequest>
{
  static const char* value()
  {
    return DataType< ::whi_interfaces::WhiSrvJointPose >::value();
  }
  static const char* value(const ::whi_interfaces::WhiSrvJointPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::whi_interfaces::WhiSrvJointPoseResponse> should match
// service_traits::MD5Sum< ::whi_interfaces::WhiSrvJointPose >
template<>
struct MD5Sum< ::whi_interfaces::WhiSrvJointPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::whi_interfaces::WhiSrvJointPose >::value();
  }
  static const char* value(const ::whi_interfaces::WhiSrvJointPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::whi_interfaces::WhiSrvJointPoseResponse> should match
// service_traits::DataType< ::whi_interfaces::WhiSrvJointPose >
template<>
struct DataType< ::whi_interfaces::WhiSrvJointPoseResponse>
{
  static const char* value()
  {
    return DataType< ::whi_interfaces::WhiSrvJointPose >::value();
  }
  static const char* value(const ::whi_interfaces::WhiSrvJointPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WHI_INTERFACES_MESSAGE_WHISRVJOINTPOSE_H
