// Generated by gencpp from file whi_interfaces/WhiSrvPartialDischargeRequest.msg
// DO NOT EDIT!


#ifndef WHI_INTERFACES_MESSAGE_WHISRVPARTIALDISCHARGEREQUEST_H
#define WHI_INTERFACES_MESSAGE_WHISRVPARTIALDISCHARGEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace whi_interfaces
{
template <class ContainerAllocator>
struct WhiSrvPartialDischargeRequest_
{
  typedef WhiSrvPartialDischargeRequest_<ContainerAllocator> Type;

  WhiSrvPartialDischargeRequest_()
    : addr(0)  {
    }
  WhiSrvPartialDischargeRequest_(const ContainerAllocator& _alloc)
    : addr(0)  {
  (void)_alloc;
    }



   typedef int32_t _addr_type;
  _addr_type addr;





  typedef boost::shared_ptr< ::whi_interfaces::WhiSrvPartialDischargeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::whi_interfaces::WhiSrvPartialDischargeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WhiSrvPartialDischargeRequest_

typedef ::whi_interfaces::WhiSrvPartialDischargeRequest_<std::allocator<void> > WhiSrvPartialDischargeRequest;

typedef boost::shared_ptr< ::whi_interfaces::WhiSrvPartialDischargeRequest > WhiSrvPartialDischargeRequestPtr;
typedef boost::shared_ptr< ::whi_interfaces::WhiSrvPartialDischargeRequest const> WhiSrvPartialDischargeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::whi_interfaces::WhiSrvPartialDischargeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::whi_interfaces::WhiSrvPartialDischargeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::whi_interfaces::WhiSrvPartialDischargeRequest_<ContainerAllocator1> & lhs, const ::whi_interfaces::WhiSrvPartialDischargeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.addr == rhs.addr;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::whi_interfaces::WhiSrvPartialDischargeRequest_<ContainerAllocator1> & lhs, const ::whi_interfaces::WhiSrvPartialDischargeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace whi_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::whi_interfaces::WhiSrvPartialDischargeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::whi_interfaces::WhiSrvPartialDischargeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whi_interfaces::WhiSrvPartialDischargeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whi_interfaces::WhiSrvPartialDischargeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whi_interfaces::WhiSrvPartialDischargeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whi_interfaces::WhiSrvPartialDischargeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::whi_interfaces::WhiSrvPartialDischargeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4383f707745e4bd672d4a1b1b3a8c43a";
  }

  static const char* value(const ::whi_interfaces::WhiSrvPartialDischargeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4383f707745e4bd6ULL;
  static const uint64_t static_value2 = 0x72d4a1b1b3a8c43aULL;
};

template<class ContainerAllocator>
struct DataType< ::whi_interfaces::WhiSrvPartialDischargeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "whi_interfaces/WhiSrvPartialDischargeRequest";
  }

  static const char* value(const ::whi_interfaces::WhiSrvPartialDischargeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::whi_interfaces::WhiSrvPartialDischargeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 addr\n"
;
  }

  static const char* value(const ::whi_interfaces::WhiSrvPartialDischargeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::whi_interfaces::WhiSrvPartialDischargeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.addr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WhiSrvPartialDischargeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::whi_interfaces::WhiSrvPartialDischargeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::whi_interfaces::WhiSrvPartialDischargeRequest_<ContainerAllocator>& v)
  {
    s << indent << "addr: ";
    Printer<int32_t>::stream(s, indent + "  ", v.addr);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHI_INTERFACES_MESSAGE_WHISRVPARTIALDISCHARGEREQUEST_H
