// Generated by gencpp from file whi_interfaces/WhiSrvPartialDischarge.msg
// DO NOT EDIT!


#ifndef WHI_INTERFACES_MESSAGE_WHISRVPARTIALDISCHARGE_H
#define WHI_INTERFACES_MESSAGE_WHISRVPARTIALDISCHARGE_H

#include <ros/service_traits.h>


#include <whi_interfaces/WhiSrvPartialDischargeRequest.h>
#include <whi_interfaces/WhiSrvPartialDischargeResponse.h>


namespace whi_interfaces
{

struct WhiSrvPartialDischarge
{

typedef WhiSrvPartialDischargeRequest Request;
typedef WhiSrvPartialDischargeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WhiSrvPartialDischarge
} // namespace whi_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::whi_interfaces::WhiSrvPartialDischarge > {
  static const char* value()
  {
    return "ecc8f660b258f268674c5e5e9427cd77";
  }

  static const char* value(const ::whi_interfaces::WhiSrvPartialDischarge&) { return value(); }
};

template<>
struct DataType< ::whi_interfaces::WhiSrvPartialDischarge > {
  static const char* value()
  {
    return "whi_interfaces/WhiSrvPartialDischarge";
  }

  static const char* value(const ::whi_interfaces::WhiSrvPartialDischarge&) { return value(); }
};


// service_traits::MD5Sum< ::whi_interfaces::WhiSrvPartialDischargeRequest> should match
// service_traits::MD5Sum< ::whi_interfaces::WhiSrvPartialDischarge >
template<>
struct MD5Sum< ::whi_interfaces::WhiSrvPartialDischargeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::whi_interfaces::WhiSrvPartialDischarge >::value();
  }
  static const char* value(const ::whi_interfaces::WhiSrvPartialDischargeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::whi_interfaces::WhiSrvPartialDischargeRequest> should match
// service_traits::DataType< ::whi_interfaces::WhiSrvPartialDischarge >
template<>
struct DataType< ::whi_interfaces::WhiSrvPartialDischargeRequest>
{
  static const char* value()
  {
    return DataType< ::whi_interfaces::WhiSrvPartialDischarge >::value();
  }
  static const char* value(const ::whi_interfaces::WhiSrvPartialDischargeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::whi_interfaces::WhiSrvPartialDischargeResponse> should match
// service_traits::MD5Sum< ::whi_interfaces::WhiSrvPartialDischarge >
template<>
struct MD5Sum< ::whi_interfaces::WhiSrvPartialDischargeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::whi_interfaces::WhiSrvPartialDischarge >::value();
  }
  static const char* value(const ::whi_interfaces::WhiSrvPartialDischargeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::whi_interfaces::WhiSrvPartialDischargeResponse> should match
// service_traits::DataType< ::whi_interfaces::WhiSrvPartialDischarge >
template<>
struct DataType< ::whi_interfaces::WhiSrvPartialDischargeResponse>
{
  static const char* value()
  {
    return DataType< ::whi_interfaces::WhiSrvPartialDischarge >::value();
  }
  static const char* value(const ::whi_interfaces::WhiSrvPartialDischargeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WHI_INTERFACES_MESSAGE_WHISRVPARTIALDISCHARGE_H
