; Auto-generated. Do not edit!


(cl:in-package whi_interfaces-msg)


;//! \htmlinclude PoseRegistrationFeedback.msg.html

(cl:defclass <PoseRegistrationFeedback> (roslisp-msg-protocol:ros-message)
  ((feedback
    :reader feedback
    :initarg :feedback
    :type cl:fixnum
    :initform 0))
)

(cl:defclass PoseRegistrationFeedback (<PoseRegistrationFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PoseRegistrationFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PoseRegistrationFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name whi_interfaces-msg:<PoseRegistrationFeedback> is deprecated: use whi_interfaces-msg:PoseRegistrationFeedback instead.")))

(cl:ensure-generic-function 'feedback-val :lambda-list '(m))
(cl:defmethod feedback-val ((m <PoseRegistrationFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader whi_interfaces-msg:feedback-val is deprecated.  Use whi_interfaces-msg:feedback instead.")
  (feedback m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<PoseRegistrationFeedback>)))
    "Constants for message type '<PoseRegistrationFeedback>"
  '((:PROC_STANDBY . 0)
    (:PROC_ACTING . 1))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'PoseRegistrationFeedback)))
    "Constants for message type 'PoseRegistrationFeedback"
  '((:PROC_STANDBY . 0)
    (:PROC_ACTING . 1))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PoseRegistrationFeedback>) ostream)
  "Serializes a message object of type '<PoseRegistrationFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'feedback)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PoseRegistrationFeedback>) istream)
  "Deserializes a message object of type '<PoseRegistrationFeedback>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'feedback)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PoseRegistrationFeedback>)))
  "Returns string type for a message object of type '<PoseRegistrationFeedback>"
  "whi_interfaces/PoseRegistrationFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PoseRegistrationFeedback)))
  "Returns string type for a message object of type 'PoseRegistrationFeedback"
  "whi_interfaces/PoseRegistrationFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PoseRegistrationFeedback>)))
  "Returns md5sum for a message object of type '<PoseRegistrationFeedback>"
  "2368efd674a454a566d52616ea8f445d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PoseRegistrationFeedback)))
  "Returns md5sum for a message object of type 'PoseRegistrationFeedback"
  "2368efd674a454a566d52616ea8f445d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PoseRegistrationFeedback>)))
  "Returns full string definition for message of type '<PoseRegistrationFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%uint8 PROC_STANDBY=0~%uint8 PROC_ACTING=1~%uint8 feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PoseRegistrationFeedback)))
  "Returns full string definition for message of type 'PoseRegistrationFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%uint8 PROC_STANDBY=0~%uint8 PROC_ACTING=1~%uint8 feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PoseRegistrationFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PoseRegistrationFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PoseRegistrationFeedback
    (cl:cons ':feedback (feedback msg))
))
