; Auto-generated. Do not edit!


(cl:in-package whi_interfaces-msg)


;//! \htmlinclude PoseRegistrationResult.msg.html

(cl:defclass <PoseRegistrationResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:fixnum
    :initform 0))
)

(cl:defclass PoseRegistrationResult (<PoseRegistrationResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PoseRegistrationResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PoseRegistrationResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name whi_interfaces-msg:<PoseRegistrationResult> is deprecated: use whi_interfaces-msg:PoseRegistrationResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <PoseRegistrationResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader whi_interfaces-msg:result-val is deprecated.  Use whi_interfaces-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<PoseRegistrationResult>)))
    "Constants for message type '<PoseRegistrationResult>"
  '((:RES_SUCCEED . 0)
    (:RES_FAILED . 1))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'PoseRegistrationResult)))
    "Constants for message type 'PoseRegistrationResult"
  '((:RES_SUCCEED . 0)
    (:RES_FAILED . 1))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PoseRegistrationResult>) ostream)
  "Serializes a message object of type '<PoseRegistrationResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'result)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PoseRegistrationResult>) istream)
  "Deserializes a message object of type '<PoseRegistrationResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'result)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PoseRegistrationResult>)))
  "Returns string type for a message object of type '<PoseRegistrationResult>"
  "whi_interfaces/PoseRegistrationResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PoseRegistrationResult)))
  "Returns string type for a message object of type 'PoseRegistrationResult"
  "whi_interfaces/PoseRegistrationResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PoseRegistrationResult>)))
  "Returns md5sum for a message object of type '<PoseRegistrationResult>"
  "14c541d6e20ea9bda2ff12e0262911aa")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PoseRegistrationResult)))
  "Returns md5sum for a message object of type 'PoseRegistrationResult"
  "14c541d6e20ea9bda2ff12e0262911aa")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PoseRegistrationResult>)))
  "Returns full string definition for message of type '<PoseRegistrationResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%uint8 RES_SUCCEED=0~%uint8 RES_FAILED=1~%uint8 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PoseRegistrationResult)))
  "Returns full string definition for message of type 'PoseRegistrationResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%uint8 RES_SUCCEED=0~%uint8 RES_FAILED=1~%uint8 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PoseRegistrationResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PoseRegistrationResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PoseRegistrationResult
    (cl:cons ':result (result msg))
))
